<div class="committees">
    <div class="row orange-70 content">
        <div class="breadcrumb">
            <p>home > committees > cjtf</p>
        </div>
        <div class="section-title double-line">
            <h2>Combined Joint Task Force<br/>Operation Inherent Resolve</h2>
        </div>
    </div>
    <div class="row orange-50 section-p content">
        <div class="col-lg-12">
            <p>The Combined Joint Task Force – Operation Inherent Resolve was established in early December 2014 in order to coordinate and oversee US and coalition missions in Syria and Iraq aimed against the Islamic State in Iraq and Syria (ISIS). The command is led by the United States but is composed by tens of western and regional allies. </p>
            <p>Born from the Iraqi and Syrian civil wars, ISIS militants had launched an aggressive and successful campaign of territorial expansion from June and July 2014. It has achieved stunning and decisive victories, declared its intention to create a Worldwide Caliphate and spread the fighting to other countries outside the Levant region, such as Libya. A myriad of regional countries and groups soon began to respond to this menace and engaged in direct or indirect fight against ISIS. Reports indicating mass civilian massacres in the territories under its control and spectacular hostage executions recorded and exhibited worldwide made even more countries prompt to intervene. </p>
            <p>The United States started airstrike missions by August which soon evolved to a broader air campaign, with the assistance of several partners. About 12 countries are launching multinational airstrikes against ISIS positions in Syria and Iraq and more than 60 nations are involved in one way or another, conducting airstrikes, sending humanitarian missions, dispatching Special Forces to assist Iraqi troops or providing financial or logistical support to the coalition military operations. The Combined Joint Task Force is now responsible by a large spectrum of activities, including airstrikes against ISIS targets, humanitarian aid, training of Iraqi troops and support provision to Kurdish militias. </p>
            <p>Although it seems a consensus that ISIS must be contained and defeated, there are different long term objectives and political agendas at stake among the mosaic of countries that compose the coalition. The command shall face the challenge that such disparities represent while conducting a military campaign in two different civil wars against a terrorist state and also deal with the implications of the expansion of such conflict to the entire region.   </p>
            <p>In this cabinet committee, delegations will take the roles of relevant authorities from selected members of the Task Force (United States, United Kingdom, France, Saudi Arabia, Jordan, United Arab Emirates and the North Atlantic Treaty Organization). Delegations are expected to utilize their expertise and resources available in both military and intelligence assets to pursue their given assignments in the most rapid, precise and efficient manner. Furthermore, it is under their competence to manage punctual crisis or mishaps that may affect their mission during the extension of the simulation. </p>            <p>Delegations will have to draw upon two operational plans during the simulation, which are related to the Task Force’s objectives. On one hand, they will have to give support in retaking an Iraqi city from the hands of ISIS’ forces; on the other, it will be necessary to decide whether it is better to destroy or retake a refinery site in Syrian territory, which is being used by ISIS but is also aimed by the forces of Assad’s regime. In both cases, besides the necessity of having full assessment of the situation on the ground, delegations will have to bear in mind the complex political situation of the Middle East. The Task Force indirect collaboration relation with Iranian-influenced Shia militias and the Kurd’s Peshmerga in Iraq, which happen to have common goals, may enter in shock with the confrontational stance of the Task Force against Assad and Hezbollah’s forces, even if they are also fighting against ISIS in Syria. Therefore, the mission laid for the delegations will be complex and challenging, but necessary to address such pressing issue of the Middle East.</p>

        </div>
    </div>

</div>
