<div id="committees">
    <div class="row orange-70 content">
        <div class="breadcrumb">
            <p>home > committees > uacps</p>
        </div>
        <div class="section-title double-line">
            <h2>Conselho de Paz e Segurança<br/>da União Africana</h2>
        </div>
    </div>
    <div class="row orange-50 section-p content">
        <div class="col-lg-12">
            <p>A União Africana (UA), criada em 2002, tem origem na Organização da Unidade Africana, um organismo regional que surgiu no período de fim da dominação europeia no continente, na tentativa de proporcionar estabilidade política aos novos países que se integravam, então, ao Sistema Internacional. A fraqueza da instituição, porém, tornou necessária a criação de um novo organismo. Surge, assim, a União Africana, a qual tem como principal objetivo promover a cooperação nas questões de segurança para que se alcance o desenvolvimento africano nos campos social, político, econômico e cultural. Trazendo uma nova mentalidade por parte dos membros, a UA vem trabalhando na tentativa de diminuir, cada vez mais, as intervenções estrangeiras nos assuntos internos ao continente. </p>
            <p>O Conselho de Paz e Segurança foi criado em 26 de Dezembro de 2003, após ser ratificado pela maioria requerida dos Estados-membros da organização. O órgão conta com quinze membros, todos rotativos e eleitos pela Assembleia Geral da organização, porém com mandatos diferentes. Cinco desses membros concorrem a um mandato de três anos, enquanto os outros dez, intercaladamente, são eleitos para mandatos de dois anos. Apesar de se espelhar no Conselho de Segurança das Nações Unidas, no CPS nenhum dos membros integrantes do conselho tem poder de veto, tornando o organismo um tanto mais democrático que aquele que o inspirou (União Africana 2015).</p>
            <p>Como seu próprio nome sugere, o Conselho de Paz e Segurança foi criado com o objetivo de manter a estabilidade do continente. Nesse sentido, esse é o órgão responsável por analisar a necessidade e, caso preciso, aprovar a implementação de missões de manutenção de paz ou intervenções rápidas em países-membros que estejam passando por conflitos civis, em que sejam confirmados casos de genocídio, crimes de guerra ou crimes contra a humanidade (União Africana 2015). Essas missões de paz protagonizadas pela União Africana, em conjunto com tropas da ONU, têm garantido um forte protagonismo da organização frente aos problemas regionais, de modo que caminha na direção correta para a eliminação gradual da influência externa no continente (Santos 2011). </p>
            <p class="references">
                Referências: Santos, Luís Ivaldo V. G. “A Arquitetura de Paz e Segurança Africana.” Fundação Alexandre Gusmão, 2011: 204.
                | União Africana. Peace and Security. Disponível em <www.au.int>. Acesso em 7 Fev 2015.

            </p>
        </div>
    </div>
    <div class="row orange section-p content">
            <div class="col-lg-6">
                <h6>Tópico A: <br/>Grupos militares não estatais no Saara-Sahel</h6>
                <p>A importância do Norte e do Oeste da África para as relações internacionais esteve profundamente vinculada ao fornecimento de hidrocarbonetos para o mercado global, sendo Nigéria, Líbia e Argélia os maiores produtores de petróleo da área. No entanto, a relevância dos países da região deixou de ser somente comercial e passou a representar um caráter militar-estratégico com os atentados de 11 de Setembro, nos EUA. O lançamento da Guerra Global ao Terror (GWoT) pela Administração Bush centrou-se no Oriente Médio, mas englobou também o Norte da África por algumas de suas características, como a fragilidade estatal (principalmente nas áreas desérticas), o antiamericanismo, a proximidade territorial da Europa e prováveis ligações das populações indígenas com as culturas árabes e islâmicas, o que facilitaria o recrutamento para grupos militares extremistas (Maglia 2013: 48).</p>
	            <p>Nesse contexto, a violência tem se expandido pela região do Saara e do Sahel, situação que contrasta com o declínio do número de conflitos armados no continente africano desde o início do século XXI. A militarização da região pela GWoT coincide com a emergência de grupos armados como o Al Qaeda no Magreb Islâmico (AQIM) e conflitos entre as Forças Armadas dos países da região e grupos insurgentes, como os Tuaregues do Mali, e a oposição armada na Líbia, e atualmente. Claramente, muitas das fontes de violência da região têm dimensões transnacionais e acabam por causar a instabilidade de vários países, demandando respostas regionais para o problema (OECD/SWAC 2014: 64 a 66).  </p>
                <p>A situação regional se tornou ainda mais delicada após a queda de Kadafi, na Líbia, e da crise no Mali. Atualmente o que tem chamado a atenção internacional para a região são as ações do grupo Boko Haram. O grupo ficou mundialmente conhecido com as repercussões do rapto de mais de 200 meninas nigerianas, em 2014, e, mais recentemente, com a morte de cerca de 2000 pessoas na cidade de Baga, em janeiro de 2015. Ao mesmo tempo em que o governo nigeriano do Presidente Goodluck Jonathan negou a ajuda oferecida pelos Estados Unidos, o país também parece não estar tomando as ações necessárias para o combate ao Boko Haram. Esta questão torna-se ainda mais problemática levando em consideração que as ações do grupo têm expandido seu escopo, atingindo países como Camarões.</p>
                <p>Esse tema traz à tona a discussão a respeito da capacidade dos Estados resolverem este tipo de problema, bem como as possíveis intervenções extrarregionais quando a situação pode ser considerada uma ameaça a uma grande potência, particularmente Estados Unidos. Atualmente uma das questões mais relevantes é a possível ajuda militar que a Rússia estaria negociando com o Camarões, para combate ao Boko Haram. A entrada da Rússia no jogo significaria o retorno do país ao continente africano, ainda mais em uma região tão estratégica para as potências europeias e os Estados Unidos, podendo modificar toda a conjuntura regional, onde potências como França, EUA e China já atuam.</p>
                <p>Como dito anteriormente, a presença de diversos grupos militares não estatais na região do Saara e do Sahel acaba trazendo a região para o centro das ações da Guerra ao Terror dos Estados Unidos. Embora a situação nesta região esteja um pouco na margem em razão das atividades do Estado Islâmico, as recentes ações do Boko Haram podem trazer esta região para o palco das intervenções extrarregionais mais uma vez. Neste sentido, é imprescindível a discussão a respeito do papel dos Estados em resolver estes problemas, e da União Africana, como fórum regional. A ideia do tópico é trazer para o debate a origem destes grupos e sua relação com as potências extrarregionais, e o processo de resolução destes problemas via União Africana.</p>

                <p class="references">
                    Referências: Maglia, Cristiana. O Saara como uma nova fronteira para o terrorismo. Trabalho de conclusão, Porto Alegre: Universidade Federal do Rio Grande do Sul, 2013.
	                | OECD/SWAC. An Atlas of the Sahara-Sahel: Geography, Economics and Security. West African Studies, OECD Publishing, 2014. Disponível em: http://www.keepeek.com/Digital-Asset-Management/oecd/agriculture-and-food/an-atlas-of-the-sahara-sahel_9789264222359-en#page3. Acesso em: 05/02/2015.
                </p>
            </div>
            <div class="col-lg-6">
                <h6>Tópico B: <br/>A Situação na Líbia</h6>
                <p>O território que é hoje conhecido como Líbia já foi ocupado por diferentes povos. Foi somente em 643, com a invasão árabe, que o hoje Estado líbio incorporou o Islã e a língua árabe a sua cultura. Seu território é tradicionalmente dividido em três províncias, a saber, a Tripolitânia (noroeste) - onde está localizada a maior cidade e também a capital do país, Trípoli - a Cirenaica (leste) e Fezzan-Ghadames (sudoeste). A Líbia apresenta, atualmente, uma população de cerca de 6.244.000 pessoas, dos quais 97% têm origem berbere ou árabe, aproximadamente o mesmo número que corresponde à quantidade de mulçumanos no total da população (CIA Factbook, 2015).</p>
                <p>Por mais de quarenta anos, a Líbia foi governada por Muammar Kadaffi. Em 2011, quando estavam em cursos os levantes que ficaram conhecidos como Primavera Árabe, Muammar Kadaffi foi derrubado: em agosto, forças da Organização do Tratado do Atlântico Norte (OTAN), rebeldes líbios e demais forças estrangeiras tomaram Trípoli, e, em outubro do mesmo ano, o ex-presidente líbio foi morto. Após a morte de Kadaffi, a administração do país fora assumida pelo Conselho Nacional de Transição (CNT), formado majoritariamente por rebeldes líbios. O CNT seria substituído, em 2012, pelo Congresso Nacional Geral (CNG), o qual fora incumbido da responsabilidade de elaborar uma Constituição para o país até o ano de 2014. Entretanto, Ali Zeidan, então Primeiro Ministro do CNG, é derrubado por milícias líbias em março de 2014, acusado de não conseguir manter a estabilidade no país; em seu lugar, assume Abdullah al-Thani. Em agosto de 2014, o CNG é substituído por uma nova casa legislativa, a House of Representatives (HoR). Entretanto, o governo de al-Thani não logrou, até hoje, exercer a administração plena de todo o território líbio, nem exercer o monopólio da força no país.</p>
                <p>Ainda em agosto de 2014, membros do antigo CNG não reconhecem o governo de al-Thani e proclamam Omar al-Hasi Primeiro Ministro. Conjuntamente com a milícia islâmica Fajr Libya e outros grupos islâmicos e tuaregues, os apoiadores de as-Hasi tomaram os prédios públicos da administração de Trípoli. Frente a isto, a HoR foge da capital do país e se instala na cidade de Tobruk, a leste. Constituem-se, portanto, dois governos paralelos na Líbia. Além disso, o governo de al-Thani também está em combate para a retomada da Cirenaica, região que clama historicamente por independência. Capitaneada pelo General Khalifa Haftar, a Operação Dignidade tem como objetivo a retomada da região da mão de grupos jihadistas como o Ansar al-Sharia, principalmente a cidade de Benghazi.</p>
                <p>Frente a este cenário, é essencial que o Conselho de Paz e Segurança da União Africana (CPSUA) dê uma resposta à situação de extrema instabilidade que a Líbia vive. Hoje o país está assolado por uma enorme violência, que já gerou e continua gerando a morte de milhões de pessoas. Além disso, a instabilidade na Líbia gera o transbordamento da violência para demais regiões, especialmente do norte da África. Cabe aos membros do Conselho de Paz e Segurança da União Africana debater soluções para a retomada da normalidade do país, para a consecução da estabilidade, na tentativa de garantir um dos objetivos centrais da organização: buscar soluções próprias para os problemas internos do continente, evitando cada vez mais  a influência de potências estrangeiras na crise líbia.</p>

                <p class="references">
                    Referências: Africa Confidential. “A tale of two cities.” Africa Confidential: Libya. 5 de Dezembro de 2014. http://www.africa-confidential.com/article/id/5862/A_tale_of_two_cities (acesso em 5 de Fevereiro de 2015).
                    | —. “Parliament at sea.” Africa Confidential: Libya. 14 de Agosto de 2014. http://www.africa-confidential.com/article-preview/id/5752/Parliaments_at_sea (acesso em 27 de Janeiro de 2015).
                    | Bandeira, Luiz Alberto Moniz. A Segunda Guerra Fria: geopolítica e dimensão estratégica dos EUA - das rebeliões na Eurásia à África do Norte e Oriente Médio. Rio de Janeiro: José Olympio Ltda. , 2013.
                    | BBC — Libya country profile. Available in: http://news.bbc.co.uk/2/hi/africa/country_profiles/819291.stm .
                    | Blanchard, Christopher M. Libya: Unrest and U.S. Policy. Congressional Research Service. 2011. Available at: http://www.fas.org/sgp/crs/row/RL33142.pdf.
                    | Campbell, Horace. Global NATO and the Catastrophic Failure in Libya: Lessons from Africa in the forging African Union. Nova Iorque: Monthly Review Press, 2013.
                    | CIA World Factbook. Libya. Available at: https://www.cia.gov/library/publications/the-world-factbook/geos/bm.html.
                    | Da Silveira, Isadora Loreto; Spohr, Alexandre; Olmedo, Luiza; Soares, Josuá Gihad; Barão, Giulia. “The Situation in Lybia”. Porto Alegre, UFRGSMUN, 2011.
                    | Hallett, Don. Petroleum Geology of Libya. Elsevier B.V. 2002.
                    | Halliday, Fred. The Middle East in International Relations — Power, Politics and Ideology. Cambridge: Cambridge University Press, 2005. 374 p.
                    | Parra, Francisco. Oil Politics: A Modern History of Petroleum. I.B. Tauris & Co. Ltd. 2004.
                    | Solomon, Hussein, e Gerrie Swart. “Libya's Foreign Policy.” African Affairs, 2005: 469-491.
                    | The Economist. France’s role in Libya: The welcome return of French diplomacy. Newsbook. News Analysis. 2011. Available at: http://www.economist.com/blogs/newsbook/2011/03/frances_role_libya.

                </p>
            </div>
    </div>
</div>
