<div class="committees">
    <div class="row orange-70 content">
        <div class="breadcrumb">
            <p>home > committees > unhrc</p>
        </div>
        <div class="section-title">
            <h2>United Nations Human Rights Council</h2>
        </div>
    </div>
    <div class="row orange-50 section-p content">
        <div class="col-lg-12">
            <p>The United Nations Human Rights Council was stablished by the General Assembly in 2006, in replacement of the Commission on Human Rights. Being a subsidiary body of the latter, this one holds the responsibility of electing its 47 members, for three-year terms, on equitable regional distribution. Resolution 60/251.8, which created the UNHRC, states that "members elected to the Council shall uphold the highest standards in the promotion and protection of human rights".</p>
	        <p>Although the Council’s resolutions are not binding, it is the most important international organ responsible for coordinating politics among countries and creating international standards on human rights. Its political and social contribution is incommensurable. This year, the delegates of this committee are invited to debate on the states’ obligation and public policies on gender perspectives and urban development.</p>
        </div>
    </div>

    <div class="row orange section-p content">
        <div class="col-md-6">
            <h6>Topic A<br/>Discussing Conflict in a Gendered Perspective:<br/>Women and the reform of the International Security Sector</h6>
            <p>Since the creation of the United Nations, it is safe to assume that the nature of warfare has changed. The development of new armaments and the increased targeting of civilians comes to attention. In said group of civilians, women suffer an inordinate amount of impact, particularly in the form of conflict-related sexual violence (CRSV), which refers to violent acts of sexual nature such as rape, sexual slavery, mutilation and strip searches. The occurrence of these types of violence is related to the belief that undisciplined militaries, police forces and other armed groups who commit said actions can act with impunity (PKSOI, 2014) . </p>
	        <p>Even though it seems natural to assume that the only way of diminishing and, eventually, ceasing violence against women is to include them in the strategic and politic decisions related to warfare, most women are still considered under qualified to deal in the matters of war or even post-conflict peace building, having their legitimacy questioned. </p>
	        <p>Fifteen years ago, the United Nations Security Council (UNSC) unanimously adopted Resolution 1325. Known as “the women resolution”, it called for all actors – state, UN, and non state – to support women’s participation in decision-making related to the prevention, management and resolution of conflict (MIT, 2010). Groundbreaking, the resolution was the first systematic insistence on the interconnectedness between gender and peace and security concerns – and asked for change in three distinctly different ways, being those the increasing of representation and active participation of women at all levels in national, regional and international institutions and mechanisms dealing with the many stages of conflict; the inclusion of a gender perspective in the planning and implementation of peace operations and negotiations, including gender-sensitive training of personnel; and finally, for the increasing attention to the protection of women from gender-based violence and the end of impunity. </p>
	        <p>For all of its status as a landmark international regulation, the resolution has been criticized by feminists for problems like gender essentialism – or the portrayal of women as perpetual victims and the annulment of their agency in both bring about and stopping violence (Sheperd, 2009). Women and children tend to be illustrated as victims to the brutality of war violence. Alas, the assumption that women are innately peaceful is still constantly used as argument for the non-participation of women in warfare decisions. Some also argue that the segregation of women’s rights from other peace and security issues tends to sideline women while institutions remain male-dominated systems. </p>
	        <p>The main criticism of the UNSCR 1325, however, lies on the fact that, since the 2000s, there is little evidence of its impacts in conflict-affected countries. Progress is seen mostly in the increase of women’s political participation, but there are still many barriers to be surpassed for the inclusion of women in the decisive matters related to global security (Nawa, 2011). It is observed that non-state and opposition movements have been more amenable to addressing issues of gender inequality in warfare than established governments. </p>
	        <p>At the United Nations Human Rights Council, delegates are called upon addressing the problems of gender inequality, gender essentialism and the exclusion of women from important decisions related to peace and security. A review of practices adopted by each country and actions to improve proactivity and collective work related to the matter done by agencies such as UN Women, UNDPA and UNDP is also intended.</p>
            <p class="references">
                References: MIT Center for International Studies. What the Women Say: Participation and UNSCR 1325. Cambridge, Massassuchets, 2010.
                | Nawa, Pretti. Resolution 1325: Evolution of Gender Perspective in UN Peacekeeping Operations. Journal of Defence Studies, Vol. 5, No. 1, 2011.
                | Peacekeeping and Stability Operations Institute. Preparing to Prevent: Conflict-Related Sexual Violence Mitigation Scenario-Based Training. US Army War College, Carlisle, Pennsylvania, 2014.
                | Sheperd, Laura J. Gender, Violence and Global Politics: Contemporary Debates in Feminist Security Studies. Political Studies Review, Vol. 7, pp. 208-219, 2009.
            </p>
        </div>
        <div class="col-md-6">
            <h6>Topic B<br/>Urban Development:<br/>Consequences to the Right to Adequate Housing</h6>
            <p>The year 2008 marked a historical turning point: for the first time, more than half the world’s population is living within urban settings. Figures point out that, by 2030, this portion will reach the percentage of approximately 80% (Crisp and Refstie 2011). Such trends prove that most cities have undergone a rapid and vertiginous development that inevitably caused changes to the urban landscape. Modern and audacious urban projects, particularly in the scenario of mega international events that well depict the global projection of cities, have taken place and accompanied this unforeseen growth – often providing cities with job opportunities, investments and wealth. A mass urbanization, though, has had a devastating impact on what concerns the right to adequate housing, as every year millions of people worldwide are forced to leave their homes for the sake of progress (COHRE 2006).</p>
            <p>Marginalized communities are those which most suffer from displacement as a consequence of major urban development projects. With a massive amount of capital flooding into cities prior to mega events, the international image of the city gains precedence over housing rights. Evictions are commonly justified as necessary for successful projects. The need for new infrastructure disproportionately affects the poor, who receive little as compensation, do not get to enjoy the benefits of the new infrastructure and are frequently relocated far away from access to basic services and assistance. Another indirect form of displacement occurs through the process of gentrification – a mega event is accompanied of increased land prices that may lead urban residents to move away from city centers in a long-term period. Gentrification-related displacement is not as immediate and apparent as evictions, but can be equally degrading to urban populations (UNHRC 2009; HRA 2010).</p>
            <p>States are obliged to provide secure tenure and protections against forced evictions – which constitute, according to the United Nations Committee on Economic, Social, and Cultural Rights, a gross violation of human rights incompatible with the State’s obligation to ensure the right to adequate housing (CESCR 1991). They are also held accountable for monitoring and punishing abuses perpetrated by private entities, as the duty to uphold international law not only applies to State-actors. In this regard, the Organization for Economic Cooperation and Development (OECD) Guidelines state that business enterprises should “[r]espect the human rights of those affected by their activities consistent with the host government’s international obligations and commitments” (OECD 2008, 14).</p>
            <p>Delegates at the United Nations Human Rights Council are called upon outlining legal obligations and public policies of State parties and private entities as to mega events and major urban projects. The debates must be run under the principle that countries should implement infrastructural development with a bias towards improving housing stock for low-income residents of a city, thus guaranteeing social integration and justice.</p>
            <p class="references">
                References: Centre on Housing Rights & Evictions (COHRE). “Global Survey on Forced Evictions: Violations of Human Rights.” 2008.
                | Committee on Economic, Social, and Cultural Rights (CESCR). United Nations. “General comment No. 4: The right to adequate housing (E/1992/23).” 1991.
                | Crisp, Jeff, and Hilde Refstie. 2011. “The urbanisation of displaced people.” Cities Alliance No. 5 – May 2011. Available at: http://www.citiesalliance.org/sites/citiesalliance.org/files/CIVIS-DisplacedPeople-July2011.pdf. Accessed 9 February 2015.
                | Human Rights Advocates (HRA). “Mega-Events, Urban Development, and Human Rights: The Duty to Prevent and Protect Against Evictions and Ensure the Right to Adequate Housing.” 2010. Available at: http://www.humanrightsadvocates.org/wp-content/uploads/2010/05/Right-to-housing-19th-session.pdf. Accessed 8 February 2015.
                | Organization for Economic Cooperation and Development (OECD). “OECD Guidelines for Multinational Enterprises.” 2008. Available at: http://www.oecd.org/corporate/mne/1922428.pdf. Accessed 9 February 2015.
                | United Nations Human Rights Council (UNHRC). United Nations. “Report of the Special Rapporteur on adequate housing as a component of the right to an adequate standard of living, and on the right to non-discrimination in this context, Raquel Rolnik (A/HRC/13/20).” 2009. Available at: http://www2.ohchr.org/english/bodies/hrcouncil/docs/13session/A-HRC-13-20.pdf. Accessed 9 February 2015.
            </p>
        </div>
    </div>
</div>
