<div class="background" id="unsc">
    <div class="row orange-70 content">
        <div class="breadcrumb">
            <p>home > committees > unsc</p>
        </div>
        <div class="section-title">
            <h2>United Nations Security Council</h2>
        </div>
    </div>
    <div class="row orange-50 section-p content">
        <div class="col-lg-12">
            <p>The UN Security Council is the primary body of the United Nations for maintaining international peace and security. One of the main characteristics of the UNSC, which contrasts with other UN organs, is that it is the only committee whose resolutions are binding upon all member states, regardless if they are current members of the UNSC or not. Moreover, it is also in the Council’s mandate the right to authorize the use of force through peacekeeping operations or military coalitions and also to impose economic and military sanctions, but always as a last resort when all negotiations have failed (especially in the case of military action). Therefore, the UNSC’s first actions when a complaint related to a threat to international peace and security is brought before it is to recommend to the parties to try and reach a peaceful solution. It may also help ceasing of the dispute by investigating or mediating the conflict. The Council has also ordered ceasefires and imposed economic sanctions or collective military embargoes on many occasions in which disputes have led to the use of force. At last, the UNSC may recommend the suspension or expulsion, by the General Assembly, of a Member State that recurrently violates the principles of the UN Charter. This committee is, then, essential for maintaining international peace and security and saving succeeding generations from the scourge of war—the main goal of the United Nations—, while its relevance goes way beyond security and geopolitics, because its decision have effects on the populations directly involved in the conflicts it strives to solve.</p>
    	    <p>The UNSC is formed by fifteen members, of which five are permanent and ten are selected by the General Assembly for two year terms. The five permanent members of the Security Council are China, France, Russian Federation, United Kingdom and United States, and they hold what is commonly known as “veto power”. That means that for any resolution to be approved it needs the concurring vote of the five “great powers”, meaning that if they are against, it will automatically fail. Current temporary members of the UNSC are Angola, Chad, Chile, Jordan, Lithuania, Malaysia, New Zealand, Nigeria, Spain and Venezuela.</p>
        </div>
    </div>
</div>

    <div class="row orange section-p content">
        <div class="col-md-6">
            <h6>Topic A<br/>THE SITUATION IN UKRAINE</h6>
            <p>Ukraine, part of the former USSR, is a country in eastern Europe that finds itself in a strategic position between Europe and Russia (Stratfor, 2014). Located in the north shore of the Black Sea, the Ukrainian territory is a major transit hub for Pan-European Corridors and for Russian pipelines that supply Europe with oil and gas, a fact that gives the country great geopolitical importance in the region (Ahmed, 2014).</p>
            <p>Today’s situation in Ukraine involves conflicts between the central government in Kiev and separatist groups, mainly from Donetsk and Lugansk, which are connected to the country’s clashes with the Russian Federation. The current crisis can be traced back to the end of 2013, when the government of Viktor Yanukovitch refused to sign a framework agreement with the European Union and accepted financial help from Russia. As a result, several popular riots broke out, protesting what they perceived as an abdication of Ukraine’s future entry into the European Union. Tensions escalated and the country came to the edge of a civil war when Yanukovitch was ousted and replaced by Petro Poroshenko, a pro-Europe politician. Further clashes opposed those in favor of Poroshenko and the alliance with EU and those in favor of Yanukovich and the connections with Russia.</p>
            <p>Under this context, the Crimean region declared itself, through a referendum, as part of the Russian Federation. This decision was supported by Moscow, since maintaining influence in its surrounding regions was considered vital to the national security and since Sebastopol, a Russian base located in Crimea, is essential for Russia’s trade and military projection in the Black Sea (Colin, 2007). The annexation of this territory, opposed by Ukraine, the USA and the European Union, created a chasm between these countries and Russia.</p>
            <p>In march, 2014, Ukraine signed an Association Agreement with the European Union and shortly after NATO suspended its cooperation with the Russian Federation. Pro-Russian protesters then took control of the eastern Ukraine provinces of Donetsk and Lugansk, which declared their independence and faced severe repression from the Kiev government. The new republics receive veiled support from Russia in the fight against the central Ukrainian government, which, by its turn, is assisted by Western countries (Mearsheimer, 2014).</p>
            <p>A cease-fire was declared in September, but the armed conflict continued and tensions escalated in Mariupol, near Crimea, due to a possible Russian desire to open a land route to Crimea through Ukraine’s southeast (Stratfor, 2015). A new cease-fire was signed in the beginning of 2015, but its future is unclear as the crisis involves the diverging interests of the European powers, NATO and Russia. </p>
            <p>Since the beginning of 2014, several sanctions, such as arms embargoes, cutoffs of gas supplies and prohibitions of trade, were unilaterally imposed on Ukraine and Crimea.  What initially was a disturbance in Ukrainian politics became a large-scale crisis, opposing Russian, European and NATO military forces in demonstrations of strength and support for their respective allies that further aggravate the situation. It is up to the UN Security Council to decide how the conflict can be solved through political means, before a new armed conflict of huge proportions once more erupts in European territory.</p>

            <p class="references">
                References: Ahmed, Nafeez. Ukraine crisis is about Great Power oil, gas pipeline rivalry. The Guardian, March 6, 2014. Available at: <http://www.theguardian.com/environment/earth-insight/2014/mar/06/ukraine-crisis-great-power-oil-gas-rivals-pipelines>. Last access on: 27/01/2015.
                | Colin, Roberto. Rússia: o ressurgimento da grande potência. Florianópolis: Letras Brasileiras, 2007.
                | Guéhenno, Jean-Marie. 10 Wars to Watch in 2015. Foreign Policy, January 2, 2015. Available at: <http://foreignpolicy.com/2015/01/02/10-wars-to-watch-in-2015/>. Last access on: 27/01/2015.
                | Mearsheimer, John J. Why the Ukraine Crisis is the West’s Fault. Foreign Affairs, September/October 2014 issue. Available at: <http://www.foreignaffairs.com/articles/141769/john-j-mearsheimer/why-the-ukraine-crisis-is-the-wests-fault>. Last access on: 27/01/2015.
                | Stratfor. Red Alert Update: At the Heart of the Mariupol Crisis. Stratfor, January 25, 2015. Available at: <http://www.stratfor.com/analysis/red-alert-update-heart-mariupol-crisis#axzz3PrPTAJaI>. Last access on: 27/01/2015.
                | __________. Ukraine’s Geographic Challenge. Stratfor Video, September 3, 2014. Available at: <http://www.stratfor.com/video/ukraines-geographic-challenge#axzz3PywdSadh>. Last access on: 27/01/2015.

            </p>
        </div>
        <div class="col-md-6">
            <h6>Topic B<br/>THE SITUATION IN YEMEN</h6>
            <p>Located in a strategic position in the oil-rich Gulf of Aden, Yemen is one of the poorest and least developed countries of the world. The port of Aden gives access to the Bab el-Mandeb strait - situated between the Arabian Peninsula and the Horn of Africa-, which is the entrance for the Red Sea and its connection to the Indian Ocean (P. F. Visentini 2012, Balanche 2014). </p>
            <p>This country of Sunni majority was divided between South and North Yemen until 1990, when a unification process took place. Yet, a separatist motivation existed in the country since 1994, when the South lost a civil war against government forces (Balanche 2014, Zimmerman 2014, P. F. Visentini 2012). Alongside with southern separatism, Yemen also had to cope with two other serious issues: a Northern Shiite insurgency, the Houthis, that started rebelling against the government in 2003; and al-Qaeda in the Arabian Peninsula (AQAP), the powerful Yemeni al-Qaeda’s branch (Mudallali 2015, Ratnam and Naylor 2015, Zimmerman 2014). </p>
            <p>A crisis erupted when the Houthi rebels took over the capital, Sana’a, and the cities of Saada and Hodeïda, and later kidnapped the president’s chief of state and seized the presidential palace. Elected in 2012, after a series of protests collapsed the former President’s regime, Abdu Rabbu Mansour Hadi cooperated very closely with the United States in order to contain the terrorist activities of the Yemeni Al-Qaeda’s affiliate, which led the country to be considered the perfect example of terrorism fight by Obama’s administration (P. G. Visentini 2014, Boot 2015, Rosen 2015). After his deposition, UNSC issued a statement recognizing Hadi as the legitimate president of Yemen, and urging that the parties solved the problem with dialoge. Nevertheless, this had almost no effects, and it did not take long before Hadi resigned and went to Aden, in the south (J.H.-R. 2014, Les Echos 2015).</p>
            <p>The resignation of the president was a shift in the balance of power in favor of the Houthis, but also a very fortunate scenario for the rise of AQAP and ISIS branches. A South secession is also a possibility, since the quasi-autonomous southern tribes are joining forces with Hadi's loyal forces to fight the shiite faction trying to rule the country. Saudi Arabia, a country that has always financed the Yemeni government, may withdraw its help if the Houthis continue to keep power on their hands, which might lead the state to collapse. The Saudis and the Yemeni media believe that the Iranian government has always helped the Northern Shiite insurrection, which may be a new reason to increase tension between Riyadh and Tehran. The latest, however, denied involvement with the Houthis when these accusations started in 2003, after the Houthis first declared war against Saleh. </p>
            <p>The United States are also extremely concerned, since without Hadi, they may have lost a potential ally on their fight against terrorism (Henderson 2015, Ratnam and Naylor 2015, Guéhenno 2015).  This issue led United States to withdraw all their remaining forces in the country, allowing AQAP and ISIS increase even more its presence and activities.</p>
            <p>Therefore, it is of great urgency that the United Nations Security Council meet again to discuss the situation in Yemen, for its unstable political situation may strongly affect the dynamics of Middle Eastern and global politics. It is extremely necessary that the countries discuss if it is possible that the Houthis become allies on the fight against terrorism, and what could be the effects in the case that the southern secession movement succeed. Both the growth of AQAP’s activities and the continuity of USA’s drone strikes on al-Qaeda targets must be a concern for the international community, as may also the devastating and worsening socioeconomic conditions of Yemeni population in such a crisis. In a context where Sunni ISIS forces keep getting strength in neighboring countries and now inside Yemen, is it possible that a common enemy like al-Qaeda can reunite longstanding opponents, as Iran and Saudi Arabia or even the United States? How will all these changes and competitions affect the international relations of the Middle East and the International System? </p>
            <p class="references">
                References: Abdul-Ahad, Ghaith. "Yemeni implosion pushes southern Sunnis into arms of al-Qaida and IsisYemeni implosion pushes southern Sunnis into arms of al-Qaida and Isis". The Guardin. March 22, 2015. http://www.theguardian.com/world/2015/mar/22/yemen-sunnis-al-qaida-isis-islamic-state-shia-houthis-sanaa (accessed March 23, 2015).
                | Balanche, Fabrice. "Le Yémen, une nouvelle partition?" Documentation Photographique: Géopolitique du Moyen-Orient, September 23, 2014: 46-47.
                | Boot, Max. "The "Yemen Model" is finished." Business Insider. January 22, 2015. http://www.businessinsider.com/the¬yemen¬model¬is¬finished¬2015¬1 (accessed February 06, 2015).
                | Guéhenno, Jean-Marie. "10 Wars to Watch in 2015." Foreign Policy. January 02, 2015. http://foreignpolicy.com/2015/01/02/10¬wars¬to¬watch¬in¬2015/ (accessed February 04, 2015).
                | Henderson, Simon. "Saudi Arabia's Nightmare is now unfolding in Yemen." Business Insider. January 21, 2015. http://www.businessinsider.com/saudi¬arabias-nightmare¬is¬now¬unfolding¬in¬yemen¬2015¬1 (accessed February 06, 2015).
                | J.H.-R. "Le Yémen s'enfonce dans la crise." LesEchos.fr. September 10, 2014. http://www.lesechos.fr/10/09/2014/LesEchos/21768¬053¬ECH_le¬yemen¬s¬enfonce-dans¬la¬crise.htm (accessed February 06, 2015).
                | Les Echos. "Le point sur la situation au Yémen." LesEchos.fr. January 20, 2015. http://www.lesechos.fr/mone/afrie¬moyen¬orient/020406404701¬le¬point¬sr¬la-sitation¬a¬yemen¬105141.php (accessed February 06, 2015).
                | Mudallali, Amal. "Why Yemen's Implosion Matters." Foreign Policy. January 22, 2015. http://foreignpolicy.com/2015/01/22/yemen-houthi-shiite (accessed February 05, 2015).
                | Ratnam, Gopal, and Séan D. Naylor. "Washington to Play Bigger Role in Yemen Terror Fight." Foreign Policy. January 26, 2015. http://foreignpolicy.com/2015/01/26/washington-to-play-bigger-role-in-yemen-terror-fight-aqap-yemen-houthis-iran-saudi-arabia/ (accessed February 06, 2015).
                | Rosen, Armin. "What Yemen Government Change Means for the U.S." Business Insider. January 22, 2015. http://www.businessinsider.com/what-¬yemen--government-¬change-¬means-¬for-¬the-¬us-2015-¬1 (accessed February 06, 2015).
                | Visentini, Paulo Fagundes. A Primavera Árabe: entre a democracia e a geopolítica do petróleo. Porto Alegre: Leitura XXI, 2012.
                | Visentini, Paulo Gilberto Fagundes. O Grande Oriente Médio - da descolonização à Primavera Arabe. Campus Elsevier, 2014.
                | Zimmerman, Katherine. Yemen's Pivotal Moment. Report, Chritical Threats Project of the American Enterprise Institute, 2014.
            </p>
        </div>
    </div>
</div>
